import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Intro from "../components/Intro";
import AboutMe from "../components/AboutMe";

export default function Home() {

  return (
    <div>
      <Head>
        <title>Rodrigo Fentanes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Intro />
      <AboutMe />
    </div>
  );
}
